import ProductOne from "../../assets/personOne.webp";
import ProductTwo from "../../assets/personTwo.webp";
import ProductThree from "../../assets/personThree.webp";
import ProductFour from "../../assets/personFour.webp";
export const Products = [
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductOne,
    category: "HOODIE - Wannabe Premium Tee",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["violet", "blue", "black"],
  },
  {
    img: ProductThree,
    category: "COAT",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductFour,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductOne,
    category: "HOODIE - Wannabe Premium Tee",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["violet", "blue", "black"],
  },
  {
    img: ProductThree,
    category: "COAT",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductFour,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductOne,
    category: "HOODIE - Wannabe Premium Tee",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["violet", "blue", "black"],
  },
  {
    img: ProductThree,
    category: "COAT",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductFour,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductOne,
    category: "HOODIE - Wannabe Premium Tee",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["violet", "blue", "black"],
  },
  {
    img: ProductThree,
    category: "COAT",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductFour,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductOne,
    category: "HOODIE - Wannabe Premium Tee",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["violet", "blue", "black"],
  },
  {
    img: ProductThree,
    category: "COAT",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductFour,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductOne,
    category: "HOODIE - Wannabe Premium Tee",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["violet", "blue", "black"],
  },
  {
    img: ProductThree,
    category: "COAT",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductFour,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductOne,
    category: "HOODIE - Wannabe Premium Tee",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["violet", "blue", "black"],
  },
  {
    img: ProductThree,
    category: "COAT",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductFour,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
  {
    img: ProductTwo,
    category: "TOPS",
    review: 2,
    star: 5,
    price: 499,
    currency: "Rs",
    color_varient: ["red", "blue", "black"],
  },
];
